spring:
  application:
    name: kafkaproducer
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      acks: all
      retries: 3
      batch-size: 16384


  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:kafkadb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console

# Kafka Topic Configuration
kafka:
  topic:
    name: ordersTopic
    partitions: 3
    replication-factor: 1

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: false

